### ISSUE TITLE
Is participation in BOTH screwing and plugging required?

### ISSUE THREAD

**Issue by abhishek47kashyap** [DavidPL1/assembly_example#16]
The challenge tracks [Bin Picking](https://www.sim4dexterity.de/en/icra-2023-competition/competition-bin-picking.html) and [Stacking](https://www.sim4dexterity.de/en/icra-2023-competition/competition-stacking.html) both explicitly state participation can be in either one or both tasks:

> Participating teams can opt to participate solely in either one or in both of these bin picking tasks.
> 
> Participating teams can opt to participate solely in either one or in both of these stacking tasks.

However, there is no such statement on the [Assembly](https://www.sim4dexterity.de/en/icra-2023-competition/competition-assembly.html) page. Does that mean participants are expected to work on both `Screwing` and `Plugging`?

Probably comes across as asking the obvious but I wanted to clarify. Thanks.

**Comment by DavidPL1** [comment]
Both these tasks are sub-tasks in the assembly track which you can register for. Participants working on both assembly tasks would be preferable, but is not required (correct me if I'm wrong @balandbal). 

Note though that the ranking for the assembly track will consider both sub-tasks, thus working on both tasks will increase your chance of winning the track.
