### ISSUE TITLE
Properties missing with Plugging task

### ISSUE THREAD

**Issue by tatsukamijo** [DavidPL1/assembly_example#17]
Although [it](https://github.com/DavidPL1/assembly_example/wiki/plugging#:~:text=Properties%20can%20be%20found%20in%20the%20rosparam%20server%20under%20the%20depicted%20name.%20To%20get%20the%20full%20path%2C%20run%20rosparam%20list%20%7C%20grep%20PROPERTY_NAME%20while%20the%20simulation%20runs.) says we can get properties in rosparam, dimensions of the plug, fixture, etc. are missing in rosparam unlike the Screwing task.

Is it expected behavior?

**Comment by balandbal** [comment]
No, this is a missing feature on our/my end. I am patching it in the next few days. I am sorry for any inconvenience.

**Comment by balandbal** [comment]
As of [version 2.2](https://github.com/DavidPL1/assembly_example/discussions/21), the parameters should be available either via a ROS interface or via our [wiki](https://github.com/DavidPL1/assembly_example/wiki/plugging). See the wiki for more details.
