### ISSUE TITLE
Availability of camera parameters (intrinsic and extrinsic)

### ISSUE THREAD

**Issue by abhishek47kashyap** [DavidPL1/assembly_example#4]
Are the intrinsic and extrinsic parameters of the 3 cameras available anywhere? This is for transforming pixel coordinates to world coordinates.

**Comment by abhishek47kashyap** [comment]
I see. I'm still on the first two difficulty levels but had a few preliminary ideas for the vision-only difficulty level that I wanted to test out. Very well, will keep an eye out for when those parameters become available in a future release.

**Comment by renyu2016** [comment]
> Publishing camera specific information with ROS on respective camera info topics (using [camera info messages](http://docs.ros.org/en/api/sensor_msgs/html/msg/CameraInfo.html)) is still a work in progress. If this feature has a high relevance for you I might raise its priority to have it included in the next release.

When would this feature be available? Or could you just list the intrinsic and extrinsic matrix here? Thanks a million!

**Comment by DavidPL1** [comment]
I have been working on this for the past week and I'm currently facing an issue where the workspace cameras seem to be fine, but the relative transforms of the gripper camera are off (see the attached image). I'm still investigating where this error originates from and as soon as I do and transforms are stable, we'll release an updated version.

![img](https://user-images.githubusercontent.com/20286447/225895760-89016c42-49d0-4ee8-ab80-b017cb697184.png)

**Comment by DavidPL1** [comment]
Good news: projections based on the camera info now seem to be correct for all cameras. Camera info topics will be included in this weeks release

**Comment by DavidPL1** [comment]
Sorry for the delay on the release, we had some bugs to hunt down beforehand.
This feature is now available in the 2.0 release. If you experience any errors regarding camera parameters, reopen this issue or create a new one.
